[package]
name = "sss"
version = "0.1.0"
authors = ["Ding Xiang Fei <dingxiangfei2009@gmail.com>"]
edition = "2018"

[dependencies]
alga = "0.9.1"
alga_derive = "0.9.1"
ndarray = "0.12.0"
ndarray-parallel = "0.9.0"
rayon = "1.2.0"
num = "0.2.0"
derive_more = "0.15.0"

[dev-dependencies]
approx = "0.3.0"
quickcheck = "0.8.0"
quickcheck_macros = "0.8.0"
